"use client";
import { useState, useEffect, useCallback } from "react";

export default function Home() {
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [mounted, setMounted] = useState(false);
  const [gateOpen, setGateOpen] = useState(false);
  const [gateDone, setGateDone] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("rta-theme") as "dark" | "light" | null;
    if (saved) setTheme(saved);
    setMounted(true);
    setTimeout(() => setGateOpen(true), 1800);
    setTimeout(() => setGateDone(true), 3200);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    document.documentElement.setAttribute("data-theme", theme);
    localStorage.setItem("rta-theme", theme);
  }, [theme, mounted]);

  const toggleTheme = useCallback(() => {
    setTheme((t) => (t === "dark" ? "light" : "dark"));
  }, []);

  useEffect(() => {
    if (!mounted) return;
    const sparkles: HTMLDivElement[] = [];
    const handleMove = (e: MouseEvent) => {
      const s = document.createElement("div");
      s.className = "sparkle-particle";
      s.style.left = e.clientX + "px";
      s.style.top = e.clientY + "px";
      document.body.appendChild(s);
      sparkles.push(s);
      setTimeout(() => { s.remove(); sparkles.splice(sparkles.indexOf(s), 1); }, 600);
    };
    window.addEventListener("mousemove", handleMove);
    return () => { window.removeEventListener("mousemove", handleMove); sparkles.forEach((s) => s.remove()); };
  }, [mounted]);

  const hexNodes = [
    { label: "Climate", icon: "\u{1F321}", angle: 0 },
    { label: "Light", icon: "\u{1F4A1}", angle: 60 },
    { label: "Security", icon: "\u{1F512}", angle: 120 },
    { label: "Garden", icon: "\u{1F33F}", angle: 180 },
    { label: "HVAC", icon: "\u{2744}", angle: 240 },
    { label: "Presence", icon: "\u{1F441}", angle: 300 },
  ];
  const cx = 400, cy = 400, r = 240;
  const getPos = (angle: number) => ({
    x: cx + r * Math.cos((angle * Math.PI) / 180),
    y: cy + r * Math.sin((angle * Math.PI) / 180),
  });

  if (!mounted) return null;

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&family=Manrope:wght@300;400;500;600;700&display=swap');
        :root{--bg:#0B0D10;--fg:#FAF9F5;--fg-muted:#A8A39D;--brass:#8B6F47;--brass-glow:rgba(139,111,71,0.3);--surface:rgba(255,255,255,0.04);--surface-border:rgba(255,255,255,0.08);--fd:'Cormorant Garamond',serif;--fb:'Manrope',sans-serif;--lux:cubic-bezier(0.16,1,0.3,1);--expo:cubic-bezier(0.87,0,0.13,1)}
        [data-theme="light"]{--bg:#FAF9F5;--fg:#0B0D10;--fg-muted:#5C5A56;--surface:rgba(0,0,0,0.03);--surface-border:rgba(0,0,0,0.08);--brass-glow:rgba(139,111,71,0.15)}
        *{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth}body{font-family:var(--fb);background:var(--bg);color:var(--fg);transition:background 0.5s ease,color 0.5s ease;overflow-x:hidden}::selection{background:var(--brass);color:#fff}
        .gate{position:fixed;inset:0;z-index:10000;pointer-events:none}.gate-l,.gate-r{position:absolute;top:0;bottom:0;width:50.1%;background:#0B0D10;will-change:transform;transition:transform 1.2s var(--expo)}.gate-l{left:0}.gate-r{right:0}.gate-open .gate-l{transform:translateX(-100%)}.gate-open .gate-r{transform:translateX(100%)}.gate-center{position:fixed;inset:0;z-index:10001;display:flex;flex-direction:column;align-items:center;justify-content:center;pointer-events:none}.gate-symbol{font-family:var(--fd);font-size:clamp(3.5rem,9vw,6.5rem);font-weight:300;color:var(--brass);opacity:0;animation:gateIn 1.2s 0.2s var(--lux) forwards}.gate-tag{font-size:0.55rem;font-weight:600;letter-spacing:0.4em;text-transform:uppercase;color:rgba(168,147,95,0.6);opacity:0;animation:gateIn 1s 0.6s var(--lux) forwards;margin-top:12px}.gate-fade{animation:gateFadeOut 0.6s 1.6s ease forwards}@keyframes gateIn{0%{opacity:0;transform:translateY(12px)}100%{opacity:1;transform:translateY(0)}}@keyframes gateFadeOut{0%{opacity:1}100%{opacity:0}}
        .sparkle-particle{position:fixed;width:4px;height:4px;background:var(--brass);border-radius:50%;pointer-events:none;z-index:99999;animation:sparkle-fade 0.6s ease-out forwards}@keyframes sparkle-fade{0%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(0)}}
        .theme-toggle{position:fixed;bottom:32px;right:32px;z-index:10000;display:flex;align-items:center;gap:8px;background:var(--surface);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid var(--surface-border);border-radius:999px;padding:8px 16px;cursor:pointer;transition:all 0.3s ease;font-family:var(--fb);font-size:0.75rem;letter-spacing:0.1em;text-transform:uppercase;color:var(--fg-muted)}.theme-toggle:hover{border-color:var(--brass);color:var(--brass)}.theme-toggle-dot{width:8px;height:8px;border-radius:50%;background:var(--brass)}
        .navbar{position:fixed;top:0;left:0;right:0;z-index:9999;display:flex;align-items:center;justify-content:space-between;padding:20px 48px;background:rgba(11,13,16,0.8);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border-bottom:1px solid var(--surface-border);transition:background 0.5s ease}[data-theme="light"] .navbar{background:rgba(250,249,245,0.85)}.nav-logo{font-family:var(--fd);font-size:1.5rem;font-weight:400;color:var(--fg);text-decoration:none;display:flex;align-items:center;gap:8px}.nav-logo b{font-weight:600}.nav-glyph{color:var(--brass);font-size:1.6rem;font-weight:600;font-family:var(--fd)}.nav-links{display:flex;gap:36px;list-style:none}.nav-links a{color:var(--fg-muted);text-decoration:none;font-size:0.85rem;letter-spacing:0.08em;text-transform:uppercase;font-weight:500;transition:color 0.3s}.nav-links a:hover{color:var(--brass)}.nav-cta{padding:10px 24px;background:var(--brass);color:#fff !important;border-radius:2px;font-size:0.8rem !important;letter-spacing:0.12em !important;text-transform:uppercase;transition:opacity 0.3s}.nav-cta:hover{opacity:0.85}
        .hero{position:relative;min-height:100vh;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:160px 24px 120px;overflow:hidden}.hero::before{content:'';position:absolute;inset:0;background:url('https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1920&q=80&auto=format&fit=crop') center/cover;opacity:0.15;z-index:0}.hero::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 0%,var(--bg) 100%);z-index:1}.hero>*{position:relative;z-index:2}.hero-badge{font-size:0.75rem;letter-spacing:0.2em;text-transform:uppercase;color:var(--brass);margin-bottom:32px;font-family:var(--fb);font-weight:600}.hero h1{font-family:var(--fd);font-size:clamp(2.8rem,6vw,5.5rem);font-weight:300;line-height:1.1;margin-bottom:28px;max-width:800px}.hero p{font-size:1.05rem;color:var(--fg-muted);max-width:560px;line-height:1.7;margin-bottom:48px}.hero-btns{display:flex;gap:16px;flex-wrap:wrap;justify-content:center}.btn-primary{padding:14px 36px;background:var(--brass);color:#fff;border:none;font-family:var(--fb);font-size:0.8rem;letter-spacing:0.14em;text-transform:uppercase;cursor:pointer;transition:opacity 0.3s}.btn-primary:hover{opacity:0.85}.btn-secondary{padding:14px 36px;background:transparent;color:var(--fg);border:1px solid var(--surface-border);font-family:var(--fb);font-size:0.8rem;letter-spacing:0.14em;text-transform:uppercase;cursor:pointer;transition:border-color 0.3s}.btn-secondary:hover{border-color:var(--brass)}.scroll-indicator{margin-top:80px;font-size:0.7rem;letter-spacing:0.2em;text-transform:uppercase;color:var(--fg-muted);opacity:0.5;animation:scroll-pulse 2s ease-in-out infinite}@keyframes scroll-pulse{0%,100%{opacity:0.3;transform:translateY(0)}50%{opacity:0.6;transform:translateY(4px)}}
        .friction-section{padding:100px 24px;text-align:center;max-width:900px;margin:0 auto}.friction-section h2{font-family:var(--fd);font-size:clamp(1.6rem,3vw,2.4rem);font-weight:300;line-height:1.5;color:var(--fg-muted)}.friction-section em{color:var(--fg);font-style:italic}
        .section-label{font-size:0.7rem;letter-spacing:0.25em;text-transform:uppercase;color:var(--brass);font-weight:600;margin-bottom:16px;font-family:var(--fb)}.section-title{font-family:var(--fd);font-size:clamp(2rem,4vw,3.2rem);font-weight:300;line-height:1.2;margin-bottom:16px}.section-subtitle{font-size:1rem;color:var(--fg-muted);line-height:1.7;max-width:560px}
        .domain-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1px;background:var(--surface-border);margin-top:64px}.domain-card{background:var(--bg);padding:48px 36px;transition:background 0.3s}.domain-card:hover{background:var(--surface)}.domain-icon{font-size:1.8rem;margin-bottom:20px}.domain-card h3{font-family:var(--fd);font-size:1.4rem;font-weight:400;margin-bottom:12px}.domain-card p{font-size:0.9rem;color:var(--fg-muted);line-height:1.6}
        .machinery-section{padding:120px 24px;text-align:center;position:relative;overflow:hidden}.machinery-svg{max-width:800px;margin:64px auto 0}.hex-node-circle{fill:var(--surface);stroke:var(--brass);stroke-width:2;transition:all 0.3s ease}.hex-node-circle:hover{fill:var(--brass-glow);stroke-width:3}.hex-label{fill:var(--fg);font-family:var(--fb);font-size:12px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase}.hex-icon{font-size:24px}.hex-line{stroke:var(--brass);stroke-width:1;opacity:0.3}.hex-center-ring{fill:none;stroke:var(--brass);opacity:0.2}.particle{fill:var(--brass);opacity:0.8}@keyframes particle-pulse{0%,100%{opacity:0.4}50%{opacity:1}}
        .hardware-section{padding:120px 24px;position:relative}.hardware-grid{display:grid;grid-template-columns:1fr 1fr;gap:80px;max-width:1200px;margin:0 auto;align-items:center}.hardware-visual{display:flex;flex-direction:column;align-items:center;gap:24px}.brass-panel-frame{width:200px;height:340px;background:linear-gradient(145deg,#A8894D,#8B6F47,#6B5535);border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:24px;box-shadow:0 20px 60px rgba(139,111,71,0.3),inset 0 1px 0 rgba(255,255,255,0.15)}.brass-btn{width:36px;height:36px;border-radius:50%;background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.15)}.brass-btn-row{display:flex;gap:20px}.panel-dim{font-size:0.7rem;color:var(--fg-muted);letter-spacing:0.15em;text-transform:uppercase}.panel-label{font-family:var(--fd);font-size:1.1rem;color:var(--fg-muted)}.hardware-specs{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}.spec-tag{padding:8px 16px;background:var(--surface);border:1px solid var(--surface-border);font-size:0.75rem;letter-spacing:0.08em;color:var(--fg-muted)}.sub-hardware-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:48px;max-width:1200px;margin-left:auto;margin-right:auto}.sub-hardware-card{padding:32px;background:var(--surface);border:1px solid var(--surface-border)}.sub-hardware-card h4{font-family:var(--fd);font-size:1.15rem;font-weight:400;margin-bottom:8px}.sub-hardware-card p{font-size:0.85rem;color:var(--fg-muted);line-height:1.5}
        .spine-quote{position:relative;padding:120px 24px;text-align:center;overflow:hidden}.spine-quote::before{content:'';position:absolute;inset:0;background:url('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80&auto=format&fit=crop') center/cover;opacity:0.1}.spine-quote>*{position:relative;z-index:1}.spine-quote h2{font-family:var(--fd);font-size:clamp(1.6rem,3vw,2.6rem);font-weight:300;line-height:1.5;max-width:700px;margin:0 auto;color:var(--fg-muted)}.spine-quote em{color:var(--fg);font-style:italic}
        .intelligence-section{padding:120px 24px;max-width:800px;margin:0 auto}.intel-steps{margin-top:64px;display:flex;flex-direction:column;gap:0}.intel-step{display:grid;grid-template-columns:60px 1fr;gap:24px;padding:40px 0;border-top:1px solid var(--surface-border)}.intel-num{font-family:var(--fd);font-size:2rem;font-weight:300;color:var(--brass)}.intel-step h3{font-family:var(--fd);font-size:1.3rem;font-weight:400;margin-bottom:12px}.intel-step h3 span{color:var(--fg-muted);font-size:0.85rem;font-family:var(--fb);margin-left:8px}.intel-step p{font-size:0.95rem;color:var(--fg-muted);line-height:1.7}.intel-prompt{margin-top:16px;padding:20px 24px;background:var(--surface);border:1px solid var(--surface-border);border-radius:4px;font-size:0.9rem;color:var(--fg);line-height:1.6}.intel-btns{display:flex;gap:12px;margin-top:12px}.intel-btn-yes{padding:8px 20px;background:var(--brass);color:#fff;border:none;font-family:var(--fb);font-size:0.75rem;letter-spacing:0.1em;cursor:pointer}.intel-btn-no{padding:8px 20px;background:transparent;color:var(--fg-muted);border:1px solid var(--surface-border);font-family:var(--fb);font-size:0.75rem;letter-spacing:0.1em;cursor:pointer}.intel-confirmed{display:flex;align-items:center;gap:8px;margin-top:16px;color:#81C784;font-size:0.85rem}
        .arch-section{padding:120px 24px;max-width:1200px;margin:0 auto}.arch-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:64px}.arch-card{padding:48px 40px;background:var(--surface);border:1px solid var(--surface-border)}.arch-card-label{font-size:0.7rem;letter-spacing:0.2em;text-transform:uppercase;color:var(--brass);font-weight:600;margin-bottom:12px}.arch-card h3{font-family:var(--fd);font-size:1.6rem;font-weight:400;margin-bottom:16px}.arch-card p{font-size:0.9rem;color:var(--fg-muted);line-height:1.7;margin-bottom:24px}.arch-feat{font-size:0.8rem;color:var(--brass);margin-bottom:6px}.stats-row{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;margin-top:48px}.stat-card{text-align:center;padding:32px 16px;background:var(--surface);border:1px solid var(--surface-border)}.stat-num{font-family:var(--fd);font-size:2.4rem;font-weight:300;color:var(--brass)}.stat-label{font-size:0.75rem;color:var(--fg-muted);margin-top:4px;letter-spacing:0.05em}
        .harmony-section{padding:80px 24px;display:flex;justify-content:center}.harmony-card{max-width:600px;width:100%;padding:48px;background:var(--surface);border:1px solid var(--surface-border);border-radius:4px;text-align:center;position:relative;overflow:hidden}.harmony-card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,transparent,var(--brass),transparent)}.harmony-status{display:inline-flex;align-items:center;gap:8px;padding:6px 16px;background:rgba(129,199,132,0.1);border:1px solid rgba(129,199,132,0.2);border-radius:999px;font-size:0.75rem;color:#81C784;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:24px}.harmony-dot{width:6px;height:6px;border-radius:50%;background:#81C784;animation:harmony-pulse 2s ease-in-out infinite}@keyframes harmony-pulse{0%,100%{opacity:0.4}50%{opacity:1}}.harmony-card h3{font-family:var(--fd);font-size:2rem;font-weight:300;margin-bottom:12px}.harmony-card p{font-size:0.9rem;color:var(--fg-muted);line-height:1.6}.harmony-domains{display:flex;justify-content:center;gap:24px;margin-top:28px;flex-wrap:wrap}.harmony-domain{font-size:0.7rem;letter-spacing:0.1em;text-transform:uppercase;color:var(--brass);opacity:0.7}
        .testimonials-section{padding:120px 24px;max-width:1200px;margin:0 auto}.testimonials-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:24px;margin-top:64px}.testimonial-card{padding:40px;background:var(--surface);border:1px solid var(--surface-border)}.testimonial-card blockquote{font-family:var(--fd);font-size:1.15rem;font-weight:300;line-height:1.7;font-style:italic;margin-bottom:24px;color:var(--fg)}.testimonial-name{font-weight:600;font-size:0.85rem;margin-bottom:4px}.testimonial-loc{font-size:0.8rem;color:var(--fg-muted)}
        .process-section{padding:120px 24px;max-width:800px;margin:0 auto}.process-steps{margin-top:64px;display:flex;flex-direction:column}.process-step{display:grid;grid-template-columns:48px 1fr;gap:24px;padding:36px 0;border-top:1px solid var(--surface-border)}.process-num{width:40px;height:40px;display:flex;align-items:center;justify-content:center;border:1px solid var(--surface-border);font-family:var(--fd);font-size:1.1rem;color:var(--brass)}.process-step h3{font-family:var(--fd);font-size:1.3rem;font-weight:400;margin-bottom:8px}.process-step p{font-size:0.9rem;color:var(--fg-muted);line-height:1.6}
        .founders-section{padding:120px 24px;max-width:900px;margin:0 auto;text-align:center}.founders-quote{font-family:var(--fd);font-size:clamp(1.3rem,2.5vw,1.8rem);font-weight:300;line-height:1.6;font-style:italic;color:var(--fg);margin:48px 0}.founders-body{font-size:0.95rem;color:var(--fg-muted);line-height:1.8;max-width:700px;margin:0 auto 48px}.founders-grid{display:flex;gap:48px;justify-content:center}.founder{text-align:center}.founder-avatar{width:72px;height:72px;border-radius:50%;background:var(--surface);border:1px solid var(--surface-border);display:flex;align-items:center;justify-content:center;font-family:var(--fd);font-size:1.4rem;color:var(--brass);margin:0 auto 12px}.founder h4{font-family:var(--fd);font-size:1.1rem;font-weight:400;margin-bottom:4px}.founder p{font-size:0.8rem;color:var(--fg-muted)}
        .cta-section{padding:120px 24px;text-align:center;max-width:600px;margin:0 auto}.cta-input-row{display:flex;gap:12px;margin-top:40px;justify-content:center}.cta-input{padding:14px 20px;background:var(--surface);border:1px solid var(--surface-border);color:var(--fg);font-family:var(--fb);font-size:0.9rem;width:300px;outline:none;transition:border-color 0.3s}.cta-input:focus{border-color:var(--brass)}.cta-input::placeholder{color:var(--fg-muted);opacity:0.5}
        .site-footer{padding:80px 48px 48px;border-top:1px solid var(--surface-border);max-width:1200px;margin:0 auto}.footer-top{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:48px;margin-bottom:64px}.footer-brand{font-family:var(--fd);font-size:1.3rem;margin-bottom:12px}.footer-tagline{font-size:0.85rem;color:var(--fg-muted);line-height:1.6}.footer-col h5{font-size:0.7rem;letter-spacing:0.2em;text-transform:uppercase;color:var(--fg-muted);margin-bottom:16px;font-weight:600}.footer-col a{display:block;color:var(--fg-muted);text-decoration:none;font-size:0.85rem;margin-bottom:10px;transition:color 0.3s}.footer-col a:hover{color:var(--brass)}.footer-bottom{display:flex;justify-content:space-between;align-items:center;padding-top:32px;border-top:1px solid var(--surface-border);font-size:0.75rem;color:var(--fg-muted)}.footer-legal a{color:var(--fg-muted);text-decoration:none;margin-left:24px;transition:color 0.3s}.footer-legal a:hover{color:var(--brass)}
        @media(max-width:768px){.navbar{padding:16px 24px}.nav-links{display:none}.hardware-grid{grid-template-columns:1fr;gap:48px}.arch-grid{grid-template-columns:1fr}.stats-row{grid-template-columns:1fr 1fr}.sub-hardware-grid{grid-template-columns:1fr}.footer-top{grid-template-columns:1fr 1fr}.cta-input-row{flex-direction:column;align-items:center}.cta-input{width:100%}}
      `}</style>

      {!gateDone && (<><div className={`gate ${gateOpen?"gate-open":""}`}><div className="gate-l"/><div className="gate-r"/></div><div className={`gate-center ${gateOpen?"gate-fade":""}`}><div className="gate-symbol">{"\u0960\u0924"}</div><div className="gate-tag">Order, naturally.</div></div></>)}

      <div className="theme-toggle" onClick={toggleTheme}><div className="theme-toggle-dot"/>{theme==="dark"?"Light":"Dark"}</div>

      <nav className="navbar"><a href="#" className="nav-logo"><span className="nav-glyph">{"\u090B"}</span>Rta <b>Living</b></a><ul className="nav-links"><li><a href="#system">System</a></li><li><a href="#hardware">Hardware</a></li><li><a href="#intelligence">AI</a></li><li><a href="#contact">Contact</a></li><li><a href="#contact" className="nav-cta">Request Access</a></li></ul></nav>

      <section className="hero"><div className="hero-badge">Complete home intelligence system</div><h1>Your entire home. One touch.</h1><p>Custom hardware. Anticipatory AI. Professional installation. Rta replaces every smart home app with a single brass panel on your wall.</p><div className="hero-btns"><button className="btn-primary">Request Installation</button><button className="btn-secondary">Watch the Film</button></div><div className="scroll-indicator">Scroll</div></section>

      <section className="friction-section"><h2>12 apps. 6 remotes. 4 voice assistants that don&rsquo;t talk to each other. <em>That&rsquo;s not a smart home. That&rsquo;s a complicated one.</em></h2></section>

      <section id="system" style={{padding:"120px 24px",maxWidth:1200,margin:"0 auto"}}><div className="section-label">The system</div><h2 className="section-title">Six domains. One brain.</h2><p className="section-subtitle">Every system in your home — from the lights to the locks — unified under a single intelligence.</p><div className="domain-grid">{[{icon:"\u{1F4A1}",name:"Lighting",desc:"Scenes, schedules, circadian rhythm. Your home matches the time of day."},{icon:"\u{1F321}",name:"Climate",desc:"Heating, cooling, ventilation. Every room at the perfect temperature."},{icon:"\u{1F512}",name:"Security",desc:"Cameras, locks, alarms. Your car arrives — the gate opens, the door unlocks."},{icon:"\u{1FA9F}",name:"Blinds",desc:"Motorized control. Dawn breaks, blinds rise. Movie starts, blackout descends."},{icon:"\u{1F3B5}",name:"Entertainment",desc:"Multi-room audio, TV. One button: projector drops, lights dim to cinema."},{icon:"\u2615",name:"Appliances",desc:"Coffee, oven, washer. Your alarm goes off — coffee brews before you stand."}].map((d)=>(<div key={d.name} className="domain-card"><div className="domain-icon">{d.icon}</div><h3>{d.name}</h3><p>{d.desc}</p></div>))}</div></section>

      <section className="machinery-section"><div className="section-label">Neural mesh</div><h2 className="section-title">The Brass Machinery</h2><p className="section-subtitle" style={{margin:"0 auto"}}>Six domains, interconnected through a single neural mesh. Every node communicates. Every signal is routed through the mind.</p><div className="machinery-svg"><svg viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg"><circle cx={cx} cy={cy} r={80} className="hex-center-ring" strokeWidth={1}/><circle cx={cx} cy={cy} r={120} className="hex-center-ring" strokeWidth={0.5}/><circle cx={cx} cy={cy} r={160} className="hex-center-ring" strokeWidth={0.3}/><text x={cx} y={cy+8} textAnchor="middle" fill="var(--brass)" fontFamily="var(--fd)" fontSize="36" fontWeight="600">{"\u090B"}</text>{hexNodes.map((node,i)=>{const p1=getPos(node.angle);return hexNodes.slice(i+1).map((node2,j)=>{const p2=getPos(node2.angle);return <line key={`l-${i}-${j}`} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} className="hex-line"/>;});})}{hexNodes.map((node,i)=>{const p=getPos(node.angle);return <line key={`cl-${i}`} x1={cx} y1={cy} x2={p.x} y2={p.y} className="hex-line" style={{opacity:0.15}}/>;})}{hexNodes.map((node,i)=>{const p1=getPos(node.angle);const p2=getPos(hexNodes[(i+1)%hexNodes.length].angle);return(<g key={`p-${i}`}><circle r={3} className="particle" style={{animation:"particle-pulse 2s ease-in-out infinite",animationDelay:`${i*0.3}s`}}><animateMotion dur={`${3+i*0.5}s`} repeatCount="indefinite" path={`M${p1.x},${p1.y} L${cx},${cy} L${p2.x},${p2.y}`}/></circle></g>);})}{hexNodes.map((node)=>{const p=getPos(node.angle);return(<g key={node.label}><circle cx={p.x} cy={p.y} r={48} className="hex-node-circle"/><text x={p.x} y={p.y-6} textAnchor="middle" className="hex-icon">{node.icon}</text><text x={p.x} y={p.y+18} textAnchor="middle" className="hex-label">{node.label}</text></g>);})}</svg></div></section>

      <section className="harmony-section"><div className="harmony-card"><div className="harmony-status"><div className="harmony-dot"/>Full Harmony</div><h3>All Systems Aligned</h3><p>Every domain is communicating. Every routine is running. Your home has achieved Rta — perfect, autonomous order.</p><div className="harmony-domains">{["Lighting","Climate","Security","Blinds","Entertainment","Appliances"].map((d)=>(<span key={d} className="harmony-domain">{d}</span>))}</div></div></section>

      <section id="hardware" className="hardware-section"><div className="hardware-grid"><div className="hardware-visual"><div className="panel-dim">86 × 146 mm</div><div className="brass-panel-frame"><div className="brass-btn-row"><div className="brass-btn"/><div className="brass-btn"/></div><div className="brass-btn-row"><div className="brass-btn"/><div className="brass-btn"/></div><div className="brass-btn-row"><div className="brass-btn"/><div className="brass-btn"/></div></div><div className="panel-label">Flagship</div></div><div><div className="section-label">Rta</div><h2 className="section-title">Rta Brass Panel</h2><p className="section-subtitle">Machined from solid brass, aged to a warm patina. No screen. No LEDs. Six haptic buttons you can find in the dark. Each press sends a subtle vibration confirming the action.</p><div className="hardware-specs">{["Solid brass","Haptic feedback","Thread / Zigbee","5-year battery","IP44 rated","OTA updates"].map((s)=>(<div key={s} className="spec-tag">{s}</div>))}</div></div></div><div className="sub-hardware-grid">{[{title:"Sensors",desc:"Temperature, motion, air quality. Hidden behind walls."},{title:"Controllers",desc:"Relays, dimmers, IR blasters. Inside your electrical panel."},{title:"Actuators",desc:"Blind motors, smart locks, valve controllers."},{title:"Rta Hub",desc:"On-premise brain. Works without internet."}].map((h)=>(<div key={h.title} className="sub-hardware-card"><h4>{h.title}</h4><p>{h.desc}</p></div>))}</div></section>

      <section className="spine-quote"><h2>The spine keeps your home alive.<br/>The mind makes it <em>intelligent.</em></h2></section>

      <section id="intelligence" className="intelligence-section"><div className="section-label">The intelligence</div><h2 className="section-title">It learns. Then it asks. Then it disappears.</h2><p className="section-subtitle">Rta never surprises you. It observes your patterns, detects routines, then asks permission before automating anything new.</p><div className="intel-steps"><div className="intel-step"><div className="intel-num">1</div><div><h3>Observe <span>· Week 1</span></h3><p>Rta watches: you dim the living room to 40% at 9:15 PM every evening. It says nothing.</p></div></div><div className="intel-step"><div className="intel-num">2</div><div><h3>Detect <span>· Day 6</span></h3><p>Pattern confirmed: &ldquo;Dim living room to 40% at ~9:15 PM&rdquo; — 5 out of 5 evenings.</p></div></div><div className="intel-step"><div className="intel-num">3</div><div><h3>Ask permission <span>· Day 7</span></h3><div className="intel-prompt">&ldquo;I noticed you dim the living room every evening around 9:15. Shall I do this automatically?&rdquo;</div><div className="intel-btns"><button className="intel-btn-yes">Yes, automate</button><button className="intel-btn-no">Not yet</button></div></div></div><div className="intel-step"><div className="intel-num">✓</div><div><h3>Automated <span>· Day 8+</span></h3><p>Approved. Runs every night on the local hub. Works even if the internet goes down.</p><div className="intel-confirmed"><span>●</span> Active — running locally</div></div></div></div></section>

      <section className="arch-section"><div className="section-label">The architecture</div><h2 className="section-title">Two layers. Unbreakable.</h2><div className="arch-grid"><div className="arch-card"><div className="arch-card-label">The spine</div><h3>Rta Hub (on-premise)</h3><p>Lives in your home. Real-time device control, offline routines, local security fallback. Internet dies? Your home keeps running.</p><div className="arch-feat">Sub-50ms response</div><div className="arch-feat">Full offline operation</div><div className="arch-feat">Encrypted local mesh</div></div><div className="arch-card"><div className="arch-card-label">The mind</div><h3>Rta Cloud Brain</h3><p>Lives in the cloud. Pattern learning, anomaly detection, new routine proposals, remote access worldwide.</p><div className="arch-feat">Learns your rhythm in days</div><div className="arch-feat">Asks before automating</div><div className="arch-feat">Access from anywhere</div></div></div><div className="stats-row">{[{num:"<50ms",label:"Response time"},{num:"100%",label:"Offline capable"},{num:"6",label:"Domains controlled"},{num:"1",label:"Touch to control all"}].map((s)=>(<div key={s.label} className="stat-card"><div className="stat-num">{s.num}</div><div className="stat-label">{s.label}</div></div>))}</div></section>

      <section className="testimonials-section"><div className="section-label">Resident voices</div><h2 className="section-title">Heard from within.</h2><div className="testimonials-grid">{[{quote:"The brass panel changed everything. My children can control any room with one button. No screens, no apps, no arguments about the remote.",name:"Arjun & Kavya Mehta",loc:"The Ritz-Carlton Residences, Mumbai"},{quote:"Rta asked me if it should start my coffee when my alarm goes off. I said yes. That was three months ago. I haven't touched the machine since.",name:"Sophia Rothschild",loc:"One Hyde Park, London"},{quote:"I travel 280 days a year. Rta runs my homes in Mumbai and London as if I never left.",name:"Priya Desai",loc:"Dual Residence, Mumbai & London"}].map((t)=>(<div key={t.name} className="testimonial-card"><blockquote>&ldquo;{t.quote}&rdquo;</blockquote><div className="testimonial-name">{t.name}</div><div className="testimonial-loc">{t.loc}</div></div>))}</div></section>

      <section className="process-section"><div className="section-label">The process</div><h2 className="section-title">White-glove installation</h2><div className="process-steps">{[{num:"1",title:"Consultation",desc:"We survey your home and design a system map for every room."},{num:"2",title:"Installation",desc:"Professional technicians install every device. 2–3 days."},{num:"3",title:"Calibration",desc:"Rta observes for 7 days and proposes its first automations."},{num:"✓",title:"Living",desc:"Your home is alive. It learns more each week. You do less each day."}].map((s)=>(<div key={s.title} className="process-step"><div className="process-num">{s.num}</div><div><h3>{s.title}</h3><p>{s.desc}</p></div></div>))}</div></section>

      <section className="founders-section"><div className="section-label">The architects</div><div className="founders-quote">&ldquo;We didn&rsquo;t build another smart home app. We built the entire system — from the brass on your wall to the cloud that thinks for you.&rdquo;</div><p className="founders-body">Rta Living was born from a refusal to accept the status quo. Smart homes aren&rsquo;t smart. They&rsquo;re fragmented. We built hardware, software, and intelligence as one — because that&rsquo;s the only way.</p><div className="founders-grid"><div className="founder"><div className="founder-avatar">JN</div><h4>Jawahar Naidu</h4><p>Co-Founder &amp; Chief Architect</p></div><div className="founder"><div className="founder-avatar">R</div><h4>Renukesh</h4><p>Co-Founder &amp; Head of Engineering</p></div></div></section>

      <section id="contact" className="cta-section"><div className="section-label">Begin your journey</div><h2 className="section-title">Request Early Access to Rta</h2><p className="section-subtitle" style={{margin:"0 auto"}}>Join a curated community of residents who believe their home should think, adapt, and serve — invisibly.</p><div className="cta-input-row"><input className="cta-input" type="email" placeholder="Your email address"/><button className="btn-primary">Request Access</button></div></section>

      <footer className="site-footer"><div className="footer-top"><div><div className="footer-brand"><span style={{color:"var(--brass)",marginRight:8}}>{"\u090B"}</span>Rta Living</div><p className="footer-tagline">Your entire home. One touch.<br/>The invisible architecture of a perfect home.</p></div><div className="footer-col"><h5>System</h5><a href="#">Lighting</a><a href="#">Climate</a><a href="#">Security</a><a href="#">Entertainment</a></div><div className="footer-col"><h5>Hardware</h5><a href="#">Brass Panels</a><a href="#">Sensors</a><a href="#">Controllers</a><a href="#">Rta Hub</a></div><div className="footer-col"><h5>Company</h5><a href="#">About</a><a href="#">Installation</a><a href="#">Contact</a><a href="#">Press</a></div></div><div className="footer-bottom"><span>© 2026 Rta Living. All rights reserved.</span><div className="footer-legal"><a href="#">Privacy</a><a href="#">Terms</a></div></div></footer>
    </>
  );
}
